/** Explicit cross-domain entry surface. Internal modules are not import targets for siblings. */
export { expandHome, isWithin, qualifiedSuiteId, resolveAgentsRoot, resolveDataRoot, resolveDshHome, resolveUserRoot, suiteDataDir } from './scanning/paths.js'
export { parseSkillFrontmatter, skillEntryRejection, stripFrontmatter } from './scanning/skills-parse.js'
export { CatalogContext } from './application/catalog-context.js'
export type { CatalogGitOptions, CatalogOptions } from './application/catalog-context.js'
export { InstallStore } from './application/install-store.js'
export { SnapshotCache } from './application/snapshot-cache.js'
export type { CatalogSnapshot } from './application/snapshot-cache.js'
export { SourceStore, codeloadTarballUrl } from './application/source-store.js'
export { discoverLspEntries } from './scanning/surfaces.js'
export { defaultMarkdownResources, resourceCommandName, resourceText } from './scanning/component-files.js'
export { settlesWithin } from './application/deadline.js'
export { migratePluginStorage } from './application/state/storage-migration.js'
export { readJsonFile, writeJsonDocument } from './application/json-file.js'
export { parseLspServers } from './scanning/lsp-spec.js'
export { expandPluginPaths, pluginPathEnvironment, pluginRootOf } from './scanning/plugin-variables.js'
export type { PluginPathContext } from './scanning/plugin-variables.js'
export { MCP_SCHEMA_ID, resolveCwd, validateAgainstSchema, validateMcpJson } from './scanning/validate.js'
export { isDirectory } from './scanning/fs-probes.js'
export { discoverSuitesInSource } from './scanning/suite-scanner.js'
export { resolveRegion } from './application/regions.js'
export { normalizeHookDocuments, standaloneHookDocument } from './scanning/project-hooks.js'
